import os
from collections import OrderedDict
import psycopg2
import yaml

DSN = 'host=db-products-prod-00 user=ecmwf_ro password=ecmwf_ro dbname=products'
with psycopg2.connect(DSN) as conn:
    with conn.cursor() as cur:
        cur.execute("SELECT DISTINCT stream, type, levtype, param::INTEGER FROM fields WHERE param != '' ORDER BY stream, type, levtype, param::INTEGER")
        rows = cur.fetchall()

index = OrderedDict()
for row in rows:
    stream, type_, levtype, param = row
    key = (stream, type_, levtype)
    if key not in index:
        index[key] = []
    index[key].append(param)

# Manually add type=tf parameters for PGEN
index[('oper', 'tf', '')] = [129, 999]
index[('enfo', 'tf', '')] = [129, 999]

yaml_dump_data = []
for key, vals in sorted(index.items()):
    if key[2]:
        yaml_dump_data.append([dict(stream=key[0], type=key[1], levtype=key[2]), vals])
    else:
        yaml_dump_data.append([dict(stream=key[0], type=key[1]), vals])

with open('params.yaml', 'w') as f:
    f.write('# File automatically generated by %s\n# Do not edit\n\n' % (os.path.basename(__file__)))
    f.write(yaml.safe_dump(yaml_dump_data, default_flow_style=False))
