#!/usr/bin/env python3
import mysql.connector
import yaml
import re
import os

# import json
db = mysql.connector.connect(host="webapps-db-prod", user="ecmwf_ro", password="ecmwf_ro", database="param")

CHEMSIDS = {}
if os.path.exists("chemids.yaml"):
    with open("chemids.yaml") as f:
        CHEMSIDSTMP = yaml.load(f.read(), Loader=yaml.FullLoader)
    # Convert list of lists to dictionary
    CHEMSIDS = {item[0]: item[1:] for item in CHEMSIDS}

cursor = db.cursor()

cursor.execute("select * from chem")

for data in cursor.fetchall():
    chemid, abbr, longname = int(data[0]), data[1].lower(), data[2].lower()

    abbr = re.sub(r"\W", "_", abbr)
    abbr = re.sub(r"_+", "_", abbr)
    abbr = re.sub(r"^_", "", abbr)
    abbr = re.sub(r"_$", "", abbr)

    if not abbr:
        abbr = "_chem_%06d" % (chemid,)

    entry = [abbr.strip(), longname.strip()]

    entry = tuple(entry)

    if chemid in CHEMSIDS:
        before = tuple(CHEMSIDS[chemid])
        if before != entry:
            print(
                "WARNING! updated chemid: {},  {} => {}".format(chemid, before, entry)
            )
            CHEMSIDS[chemid] = list(entry)
    else:
        print("new chemid: {} {}".format(chemid, entry))
        CHEMSIDS[chemid] = list(entry)

cursor.close()
db.close()

# Convert to list of lists and remove duplicates
chemid_list = []
for k, v in CHEMSIDS.items():
    ll = [k]
    for item in v:
        if item not in ll:
            ll.append(item)
    chemid_list.append(ll)

with open("chemids.yaml", "w") as f:
    f.write(
        "# File automatically generated by %s\n# Do not edit\n\n"
        % (os.path.basename(__file__))
    )
    yaml.safe_dump(chemid_list, f, default_flow_style=None)
