#!/usr/bin/env python3
import yaml
import re
import os
import json
import itertools
import subprocess


def key(when):
    k = json.dumps(when, sort_keys=True)
    k = re.sub(r'\W', '_', k)
    k = re.sub(r'_+', '_', k)
    k = re.sub(r'^_', '', k)
    k = re.sub(r'_$', '', k)
    return k


PARAMS = {}
if os.path.exists("params.yaml"):
    with open("params.yaml") as f:
        PARAMS = yaml.load(f.read())

OUT = []
if os.path.exists("prodgen-params.yaml"):
    with open("prodgen-params.yaml") as f:
        OUT = yaml.load(f.read())

EXTRA = {}
if os.path.exists("prodgen-params-extra.yaml"):
    with open("prodgen-params-extra.yaml") as f:
        extra = yaml.load(f.read())
    for w, e in extra:
        EXTRA[key(w)] = e

skip = set()
for entry in OUT:
    when, parms = entry
    skip.add(key(when))

for entry in PARAMS:
    when, parms = entry
    orig = dict(**when)

    if key(when) in skip:
        continue

    if not when:
        continue

    for k, v in list(when.items()):
        if not isinstance(v, list):
            when[k] = [v]

    target = key(when) + '.list'

    if not os.path.exists(target):

        with open('tmp', "w") as f:

            names = list(when.keys())
            values = list(when.values())

            print(when)

            for n in itertools.product(*values):
                r = dict((a, b) for a, b in zip(names, n))
                if r.get('type') in ('wp', 'cv', 'tf'):
                    continue

                if r.get('stream') == 'efov':
                    continue

                print(r)

                for levtype in ('sfc', 'pl', 'ml', 'pt', 'pv'):
                    r['levtype'] = levtype
                    r['time'] = "0/12"
                    r['date'] = "20180701/to/20180707"
                    r['hide'] = 'channel/ident/instrument/branch/frequency/direction/method/system/origin/quantile/domain/number/fcmonth/type/class/expver/stream/hdate/levtype/month/year/date/levelist/time/step/files/missing/offset/length/grand-total/cost/file/id'
                    r['target'] = target

                    rr = 'list,' + ",".join("%s=%s" % (a, b) for a, b in r.items())
                    print(rr, file=f)

        subprocess.call(["mars", "tmp"])

    params = set()
    with open(target) as f:
        lines = set(x.strip() for x in f.readlines())
        for n in lines:
            if n == '':
                continue
            if n == 'param':
                continue
            m = n.split('.')
            if len(m) == 2:
                p, t = int(m[0]), int(m[1])
                if t == 128:
                    t = 0
                m = t * 1000 + p
            elif len(m) == 1:
                m = int(m[0])
            else:
                print(m[0])
                exit(1)
            params.add(m)

    if 155 in params and 138 in params:
        params.add(131)
        params.add(132)

    if 171129 in params:
        params.add(171156)

    if 129 in params:
        params.add(156)

    for p in EXTRA.get(key(when), []):
        params.add(p)

    params = sorted(params)
    print(params)

    if not params:
        params = parms

    OUT.append([orig, params])

with open("params.yaml", "w") as f:
    f.write('# File automatically generated by %s\n# Do not edit\n\n' % (os.path.basename(__file__)))
    f.write(yaml.safe_dump(OUT, default_flow_style=False))
