# Stuff that is not archived in mars
#
- - stream: enfh
    type:
    - cf
    - pf
    - cv
  - - 1
    - 2
- - stream: enfo
    type: cm
  - - 130

- - stream: msmm
    type: em
  - - 9 # ssro
    - 8 # sro
    - 205 # ro
    - 212 # tisr


- - stream: mmsa
    type: em
  - - 39 # swvl1
    - 40 # swvl2
    - 41 # swvl3
    - 42 # swvl4

- - stream: msmm
    type: fcmean
  - - 205 # ro
    - 212 # tisr

- - stream: mmsa
    type: fcmean
  - - 39 # swvl1
    - 40 # swvl2
    - 41 # swvl3
    - 42 # swvl4