### config headers

ecbuild_generate_config_headers( DESTINATION ${INSTALL_INCLUDE_DIR}/metkit )

configure_file( metkit_config.h.in    metkit_config.h )
configure_file( metkit_version.h.in   metkit_version.h )

install(FILES
            ${CMAKE_CURRENT_BINARY_DIR}/metkit_config.h
            ${CMAKE_CURRENT_BINARY_DIR}/metkit_version.h
        DESTINATION
            ${INSTALL_INCLUDE_DIR}/metkit )

### metkit sources

list( APPEND metkit_srcs
    metkit_version.c
    config/LibMetkit.cc
    config/LibMetkit.h
    mars/BaseProtocol.cc
    mars/BaseProtocol.h
    mars/ClientTask.cc
    mars/ClientTask.h
    mars/DHSProtocol.cc
    mars/DHSProtocol.h
    mars/Matcher.cc
    mars/Matcher.h
    mars/MarsExpansion.cc
    mars/MarsExpansion.h
    mars/MarsHandle.cc
    mars/MarsHandle.h
    mars/MarsLanguage.cc
    mars/MarsLanguage.h
    mars/MarsLocation.cc
    mars/MarsLocation.h
    mars/MarsParsedRequest.cc
    mars/MarsParsedRequest.h
    mars/MarsParser.cc
    mars/MarsParser.h
    mars/MarsRequest.cc
    mars/MarsRequest.h
    mars/MarsRequestHandle.cc
    mars/MarsRequestHandle.h
    mars/Parameter.cc
    mars/Parameter.h
    mars/ParamID.cc
    mars/ParamID.h
    mars/Quantile.cc
    mars/Quantile.h
    mars/RequestEnvironment.cc
    mars/RequestEnvironment.h
    mars/StepRangeNormalise.h
    mars/Type.cc
    mars/Type.h
    mars/TypeAny.cc
    mars/TypeAny.h
    mars/TypeDate.cc
    mars/TypeDate.h
    mars/TypeEnum.cc
    mars/TypeEnum.h
    mars/TypeExpver.cc
    mars/TypeExpver.h
    mars/TypeFloat.cc
    mars/TypeFloat.h
    mars/TypeInteger.cc
    mars/TypeInteger.h
    mars/TypeLowercase.cc
    mars/TypeLowercase.h
    mars/TypeMixed.cc
    mars/TypeMixed.h
    mars/TypeParam.cc
    mars/TypeParam.h
    mars/TypeRange.cc
    mars/TypeRange.h
    mars/TypeRegex.cc
    mars/TypeRegex.h
    mars/TypesFactory.cc
    mars/TypesFactory.h
    mars/TypeTime.cc
    mars/TypeTime.h
    mars/TypeToByList.h
    mars/TypeToByListQuantile.cc
    mars/TypeToByListQuantile.h
    tool/MetkitTool.cc
    tool/MetkitTool.h
    fields/FieldIndex.cc
    fields/FieldIndex.h
    fields/FieldIndexList.cc
    fields/FieldIndexList.h
    fields/SimpleFieldIndex.cc
    fields/SimpleFieldIndex.h
    hypercube/HyperCube.cc
    hypercube/HyperCube.h
    hypercube/HyperCubePayloaded.h
    api/metkit_c.cc
    api/metkit_c.h
)

list( APPEND metkit_persistent_srcs
    mars/Param.cc
    mars/Param.h
    mars/Param
    mars/StepRange.cc
    mars/StepRange.h
    mars/StepRange
)
list( APPEND metkit_srcs ${metkit_persistent_srcs} )

if ( HAVE_GRIB )

    list( APPEND metkit_srcs
        pointdb/bits.h
        pointdb/DataSource.cc
        pointdb/DataSource.h
        pointdb/FieldIndexer.cc
        pointdb/FieldIndexer.h
        pointdb/GribDataSource.cc
        pointdb/GribDataSource.h
        pointdb/GribFieldInfo.cc
        pointdb/GribFieldInfo.h
        pointdb/GribHandleDataSource.cc
        pointdb/GribHandleDataSource.h
        pointdb/masks.h
        pointdb/PointIndex.cc
        pointdb/PointIndex.h
        codes/BUFRDecoder.cc
        codes/BUFRDecoder.h
        codes/GRIBDecoder.cc
        codes/GRIBDecoder.h
        codes/CodesDataContent.cc
        codes/CodesDataContent.h
        codes/BufrContent.cc
        codes/BufrContent.h
        codes/CodesSplitter.cc
        codes/CodesSplitter.h
        codes/CodesHandleDeleter.h

        codes/api/CodesAPI.h
        codes/api/CodesAPI.cc
        codes/api/CodesTypes.h
        codes/api/CodesTypes.cc
        codes/api/KeyIterator.h
        codes/api/KeyIterator.cc
        codes/api/GeoIterator.h
    )

    if( NOT eccodes_HAVE_GEOGRAPHY OR NOT eccodes_HAVE_ECKIT_GEO )
        list( APPEND metkit_srcs
            codes/LibEccodes.cc
            codes/LibEccodes.h
        )
    endif()

    set( grib_libs eccodes )

endif ()

if ( HAVE_ODB )

    list( APPEND metkit_srcs
            odb/IdMapper.cc
            odb/IdMapper.h
            odb/OdbToRequest.cc
            odb/OdbToRequest.h
            odb/OdbMetadataDecoder.cc
            odb/OdbMetadataDecoder.h
            odb/OdbDecoder.cc
            odb/OdbContent.cc
            odb/OdbContent.h
            odb/OdbDecoder.h
            odb/OdbSplitter.cc
            odb/OdbSplitter.h
        )
    set( odc_libs odccore )
endif()

if ( HAVE_GRIB2MARS )
    list( APPEND metkit_srcs
        grib2mars/api/Grib2Mars.cc
        grib2mars/api/Grib2Mars.h
        grib2mars/api/Grib2MarsApiErrorHandling.h
        grib2mars/mappings/Grib2MarsReturnValue.h
        grib2mars/mappings/MarsTopology.h
        grib2mars/mappings/mappings.h
        grib2mars/mappings/rules/activity.h
        grib2mars/mappings/rules/anoffset.h
        grib2mars/mappings/rules/channel.h
        grib2mars/mappings/rules/chem.h
        grib2mars/mappings/rules/class.h
        grib2mars/mappings/rules/coeffindex.h
        grib2mars/mappings/rules/dataset.h
        grib2mars/mappings/rules/date.h
        grib2mars/mappings/rules/direction.h
        grib2mars/mappings/rules/domain.h
        grib2mars/mappings/rules/experiment.h
        grib2mars/mappings/rules/expver.h
        grib2mars/mappings/rules/extract.h
        grib2mars/mappings/rules/frequency.h
        grib2mars/mappings/rules/grid.h
        grib2mars/mappings/rules/hdate.h
        grib2mars/mappings/rules/ident.h
        grib2mars/mappings/rules/instrument.h
        grib2mars/mappings/rules/iteration.h
        grib2mars/mappings/rules/levelist.h
        grib2mars/mappings/rules/levtype.h
        grib2mars/mappings/rules/method.h
        grib2mars/mappings/rules/misc.h
        grib2mars/mappings/rules/model.h
        grib2mars/mappings/rules/number.h
        grib2mars/mappings/rules/origin.h
        grib2mars/mappings/rules/packing.h
        grib2mars/mappings/rules/param.h
        grib2mars/mappings/rules/resolution.h
        grib2mars/mappings/rules/stattype.h
        grib2mars/mappings/rules/step.h
        grib2mars/mappings/rules/stream.h
        grib2mars/mappings/rules/system.h
        grib2mars/mappings/rules/time.h
        grib2mars/mappings/rules/timespan.h
        grib2mars/mappings/rules/truncation.h
        grib2mars/mappings/rules/type.h
        grib2mars/mappings/rules/wavelength.h
        grib2mars/utils/dictionary_traits/dictaccess_eckit_configuration.h
        grib2mars/utils/dictionary_traits/dictaccess_mars_request.h
        grib2mars/utils/dictionary_traits/dictionary_access_traits.h
        grib2mars/utils/generalUtils.h
        grib2mars/utils/grib2marsExceptions.h
        grib2mars/utils/logUtils.h
        grib2mars/utils/paramMatcher.h
        grib2mars/utils/type_traits_name.h
    )
endif()

if ( HAVE_MARS2MARS )
    list( APPEND metkit_srcs
        mars2mars/api/Mars2Mars.cc
        mars2mars/api/Mars2Mars.h
        mars2mars/api/Mars2MarsApiErrorHandling.h
        mars2mars/mappings/Mars2MarsReturnValue.h
        mars2mars/mappings/mappings.h
        mars2mars/mappings/rules/chemical.h
        mars2mars/mappings/rules/common.h
        mars2mars/mappings/rules/ecc-1806.h
        mars2mars/mappings/rules/incremental.h
        mars2mars/mappings/rules/local2wmo.h
        mars2mars/mappings/rules/misc-params.h
        mars2mars/mappings/rules/removeNumber.h
        mars2mars/mappings/rules/sfc2sol.h
        mars2mars/mappings/rules/timespan.h
        mars2mars/mappings/rules/waveStreams.h
        mars2mars/mappings/rules/windspeed.h
        mars2mars/utils/dictionary_traits/dictaccess_eckit_configuration.h
        mars2mars/utils/dictionary_traits/dictaccess_mars_request.h
        mars2mars/utils/dictionary_traits/dictionary_access_traits.h
        mars2mars/utils/generalUtils.h
        mars2mars/utils/logUtils.h
        mars2mars/utils/mars2marsExceptions.h
        mars2mars/utils/paramMatcher.h
        mars2mars/utils/type_traits_name.h
    )
endif()

if ( HAVE_MARS2GRIB )
    list( APPEND metkit_srcs
        mars2grib/CoreOperations.h
        mars2grib/api/Mars2Grib.cc
        mars2grib/api/Mars2Grib.h
        mars2grib/api/Options.h
        mars2grib/backend/checks/checkDerivedProductDefinitionSection.h
        mars2grib/backend/checks/checkDestinELocalSection.h
        mars2grib/backend/checks/checkEnsembleProductDefinitionSection.h
        mars2grib/backend/checks/checkLocalUseSection.h
        mars2grib/backend/checks/checkStatisticsProductDefinitionSection.h
        mars2grib/backend/checks/matchDataRepresentationTemplateNumber.h
        mars2grib/backend/checks/matchDataset.h
        mars2grib/backend/checks/matchGridDefinitionTemplateNumber.h
        mars2grib/backend/checks/matchLocalDefinitionNumber.h
        mars2grib/backend/checks/matchProductDefinitionTemplateNumber.h
        mars2grib/backend/compile-time-registry-engine/EntryVariantRegistry.h
        mars2grib/backend/compile-time-registry-engine/RegisterEntryDescriptor.h
        mars2grib/backend/compile-time-registry-engine/common.h
        mars2grib/backend/compile-time-registry-engine/makeEntryCallbacksRegistry.h
        mars2grib/backend/compile-time-registry-engine/makePhaseCallbacksRegistry.h
        mars2grib/backend/compile-time-registry-engine/makeVariantCallbacksRegistry.h
        mars2grib/backend/compile-time-registry-engine/utils.h
        mars2grib/backend/concepts/AllConcepts.h
        mars2grib/backend/concepts/EncodingCallbacksRegistry.h
        mars2grib/backend/concepts/GeneralRegistry.h
        mars2grib/backend/concepts/MatchingCallbacksRegistry.h
        mars2grib/backend/concepts/analysis/analysisConceptDescriptor.h
        mars2grib/backend/concepts/analysis/analysisEncoding.h
        mars2grib/backend/concepts/analysis/analysisEnum.h
        mars2grib/backend/concepts/analysis/analysisMatcher.h
        mars2grib/backend/concepts/brightness-temperature/brightnessTemperatureConceptDescriptor.h
        mars2grib/backend/concepts/brightness-temperature/brightnessTemperatureEncoding.h
        mars2grib/backend/concepts/brightness-temperature/brightnessTemperatureEnum.h
        mars2grib/backend/concepts/brightness-temperature/brightnessTemperatureMatcher.h
        mars2grib/backend/concepts/composition/compositionConceptDescriptor.h
        mars2grib/backend/concepts/composition/compositionEncoding.h
        mars2grib/backend/concepts/composition/compositionEnum.h
        mars2grib/backend/concepts/composition/compositionMatcher.h
        mars2grib/backend/concepts/data-type/dataTypeConceptDescriptor.h
        mars2grib/backend/concepts/data-type/dataTypeEncoding.h
        mars2grib/backend/concepts/data-type/dataTypeEnum.h
        mars2grib/backend/concepts/data-type/dataTypeMatcher.h
        mars2grib/backend/concepts/derived/derivedConceptDescriptor.h
        mars2grib/backend/concepts/derived/derivedEncoding.h
        mars2grib/backend/concepts/derived/derivedEnum.h
        mars2grib/backend/concepts/derived/derivedMatcher.h
        mars2grib/backend/concepts/destine/destineConceptDescriptor.h
        mars2grib/backend/concepts/destine/destineEncoding.h
        mars2grib/backend/concepts/destine/destineEnum.h
        mars2grib/backend/concepts/destine/destineMatcher.h
        mars2grib/backend/concepts/ensemble/ensembleConceptDescriptor.h
        mars2grib/backend/concepts/ensemble/ensembleEncoding.h
        mars2grib/backend/concepts/ensemble/ensembleEnum.h
        mars2grib/backend/concepts/ensemble/ensembleMatcher.h
        mars2grib/backend/concepts/generating-process/generatingProcessConceptDescriptor.h
        mars2grib/backend/concepts/generating-process/generatingProcessEncoding.h
        mars2grib/backend/concepts/generating-process/generatingProcessEnum.h
        mars2grib/backend/concepts/generating-process/generatingProcessMatcher.h
        mars2grib/backend/concepts/iteration/iterationConceptDescriptor.h
        mars2grib/backend/concepts/iteration/iterationEncoding.h
        mars2grib/backend/concepts/iteration/iterationEnum.h
        mars2grib/backend/concepts/iteration/iterationMatcher.h
        mars2grib/backend/concepts/level/levelConceptDescriptor.h
        mars2grib/backend/concepts/level/levelEncoding.h
        mars2grib/backend/concepts/level/levelEnum.h
        mars2grib/backend/concepts/level/levelMatcher.h
        mars2grib/backend/concepts/longrange/longrangeConceptDescriptor.h
        mars2grib/backend/concepts/longrange/longrangeEncoding.h
        mars2grib/backend/concepts/longrange/longrangeEnum.h
        mars2grib/backend/concepts/longrange/longrangeMatcher.h
        mars2grib/backend/concepts/mars/marsConceptDescriptor.h
        mars2grib/backend/concepts/mars/marsEncoding.h
        mars2grib/backend/concepts/mars/marsEnum.h
        mars2grib/backend/concepts/mars/marsMatcher.h
        mars2grib/backend/concepts/model-error/modelErrorConceptDescriptor.h
        mars2grib/backend/concepts/model-error/modelErrorEncoding.h
        mars2grib/backend/concepts/model-error/modelErrorEnum.h
        mars2grib/backend/concepts/model-error/modelErrorMatcher.h
        mars2grib/backend/concepts/nil/nilConceptDescriptor.h
        mars2grib/backend/concepts/nil/nilEncoding.h
        mars2grib/backend/concepts/nil/nilEnum.h
        mars2grib/backend/concepts/nil/nilMatcher.h
        mars2grib/backend/concepts/origin/originConceptDescriptor.h
        mars2grib/backend/concepts/origin/originEncoding.h
        mars2grib/backend/concepts/origin/originEnum.h
        mars2grib/backend/concepts/origin/originMatcher.h
        mars2grib/backend/concepts/packing/packingConceptDescriptor.h
        mars2grib/backend/concepts/packing/packingEncoding.h
        mars2grib/backend/concepts/packing/packingEnum.h
        mars2grib/backend/concepts/packing/packingMatcher.h
        mars2grib/backend/concepts/param/paramConceptDescriptor.h
        mars2grib/backend/concepts/param/paramEncoding.h
        mars2grib/backend/concepts/param/paramEnum.h
        mars2grib/backend/concepts/param/paramMatcher.h
        mars2grib/backend/concepts/point-in-time/pointInTimeConceptDescriptor.h
        mars2grib/backend/concepts/point-in-time/pointInTimeEncoding.h
        mars2grib/backend/concepts/point-in-time/pointInTimeEnum.h
        mars2grib/backend/concepts/point-in-time/pointInTimeMatcher.h
        mars2grib/backend/concepts/reference-period/referencePeriodConceptDescriptor.h
        mars2grib/backend/concepts/reference-period/referencePeriodEncoding.h
        mars2grib/backend/concepts/reference-period/referencePeriodEnum.h
        mars2grib/backend/concepts/reference-period/referencePeriodMatcher.h
        mars2grib/backend/concepts/reference-time/referenceTimeConceptDescriptor.h
        mars2grib/backend/concepts/reference-time/referenceTimeEncoding.h
        mars2grib/backend/concepts/reference-time/referenceTimeEnum.h
        mars2grib/backend/concepts/reference-time/referenceTimeMatcher.h
        mars2grib/backend/concepts/representation/representationConceptDescriptor.h
        mars2grib/backend/concepts/representation/representationEncoding.h
        mars2grib/backend/concepts/representation/representationEnum.h
        mars2grib/backend/concepts/representation/representationMatcher.h
        mars2grib/backend/concepts/satellite/satelliteConceptDescriptor.h
        mars2grib/backend/concepts/satellite/satelliteEncoding.h
        mars2grib/backend/concepts/satellite/satelliteEnum.h
        mars2grib/backend/concepts/satellite/satelliteMatcher.h
        mars2grib/backend/concepts/shape-of-the-earth/shapeOfTheEarthConceptDescriptor.h
        mars2grib/backend/concepts/shape-of-the-earth/shapeOfTheEarthEncoding.h
        mars2grib/backend/concepts/shape-of-the-earth/shapeOfTheEarthEnum.h
        mars2grib/backend/concepts/shape-of-the-earth/shapeOfTheEarthMatcher.h
        mars2grib/backend/concepts/statistics/impl/statisticsDescriptor.h
        mars2grib/backend/concepts/statistics/statisticsConceptDescriptor.h
        mars2grib/backend/concepts/statistics/statisticsEncoding.h
        mars2grib/backend/concepts/statistics/statisticsEnum.h
        mars2grib/backend/concepts/statistics/statisticsMatcher.h
        mars2grib/backend/concepts/strike-probability/strikeProbabilityConceptDescriptor.h
        mars2grib/backend/concepts/strike-probability/strikeProbabilityEncoding.h
        mars2grib/backend/concepts/strike-probability/strikeProbabilityEnum.h
        mars2grib/backend/concepts/strike-probability/strikeProbabilityMatcher.h
        mars2grib/backend/concepts/tables/tablesConceptDescriptor.h
        mars2grib/backend/concepts/tables/tablesEncoding.h
        mars2grib/backend/concepts/tables/tablesEnum.h
        mars2grib/backend/concepts/tables/tablesMatcher.h
        mars2grib/backend/concepts/wave/waveConceptDescriptor.h
        mars2grib/backend/concepts/wave/waveEncoding.h
        mars2grib/backend/concepts/wave/waveEnum.h
        mars2grib/backend/concepts/wave/waveMatcher.h
        mars2grib/backend/deductions/activity.h
        mars2grib/backend/deductions/allowedReferenceValue.h
        mars2grib/backend/deductions/backgroundProcess.h
        mars2grib/backend/deductions/bitsPerValue.h
        mars2grib/backend/deductions/centre.h
        mars2grib/backend/deductions/channel.h
        mars2grib/backend/deductions/chemId.h
        mars2grib/backend/deductions/class.h
        mars2grib/backend/deductions/componentIndex.h
        mars2grib/backend/deductions/dataset.h
        mars2grib/backend/deductions/derivedForecast.h
        mars2grib/backend/deductions/detail/ProductTime.h
        mars2grib/backend/deductions/detail/StatType.h
        mars2grib/backend/deductions/detail/StatisticalWindow.h
        mars2grib/backend/deductions/detail/pv_137_be.h
        mars2grib/backend/deductions/experiment.h
        mars2grib/backend/deductions/expver.h
        mars2grib/backend/deductions/firstWavelength.h
        mars2grib/backend/deductions/fourierCoefficientIndex.h
        mars2grib/backend/deductions/generatingProcessIdentifier.h
        mars2grib/backend/deductions/generation.h
        mars2grib/backend/deductions/instrumentType.h
        mars2grib/backend/deductions/iterationNumber.h
        mars2grib/backend/deductions/lengthOfTimeWindow.h
        mars2grib/backend/deductions/level.h
        mars2grib/backend/deductions/localTablesVersion.h
        mars2grib/backend/deductions/methodNumber.h
        mars2grib/backend/deductions/model.h
        mars2grib/backend/deductions/modelErrorType.h
        mars2grib/backend/deductions/numberOfComponents.h
        mars2grib/backend/deductions/numberOfForecastsInEnsemble.h
        mars2grib/backend/deductions/numberOfFourierCoefficients.h
        mars2grib/backend/deductions/numberOfFrequencies.h
        mars2grib/backend/deductions/offsetToEndOf4DvarWindow.h
        mars2grib/backend/deductions/paramId.h
        mars2grib/backend/deductions/periodItMax.h
        mars2grib/backend/deductions/periodItMin.h
        mars2grib/backend/deductions/perturbationNumber.h
        mars2grib/backend/deductions/productTime.h
        mars2grib/backend/deductions/productionStatusOfProcessedData.h
        mars2grib/backend/deductions/pvArray.h
        mars2grib/backend/deductions/realization.h
        mars2grib/backend/deductions/resolution.h
        mars2grib/backend/deductions/satelliteNumber.h
        mars2grib/backend/deductions/satelliteSeries.h
        mars2grib/backend/deductions/scaleFactorOfCentralWaveNumber.h
        mars2grib/backend/deductions/scaledValueOfCentralWaveNumber.h
        mars2grib/backend/deductions/shapeOfTheEarth.h
        mars2grib/backend/deductions/significanceOfReferenceTime.h
        mars2grib/backend/deductions/stream.h
        mars2grib/backend/deductions/subCentre.h
        mars2grib/backend/deductions/subSetTrunc.h
        mars2grib/backend/deductions/systemNumber.h
        mars2grib/backend/deductions/tablesVersion.h
        mars2grib/backend/deductions/timeIncrementInSeconds.h
        mars2grib/backend/deductions/totalNumberOfIterations.h
        mars2grib/backend/deductions/type.h
        mars2grib/backend/deductions/typeOfEnsembleForecast.h
        mars2grib/backend/deductions/typeOfGeneratingProcess.h
        mars2grib/backend/deductions/typeOfProcessedData.h
        mars2grib/backend/deductions/typeOfStatisticalProcessing.h
        mars2grib/backend/deductions/waveDirectionGrid.h
        mars2grib/backend/deductions/waveDirectionNumber.h
        mars2grib/backend/deductions/waveFrequencyGrid.h
        mars2grib/backend/deductions/waveFrequencyNumber.h
        mars2grib/backend/encodeValues.h
        mars2grib/backend/sections/initializers/sectionInitializer0.h
        mars2grib/backend/sections/initializers/sectionInitializer1.h
        mars2grib/backend/sections/initializers/sectionInitializer2.h
        mars2grib/backend/sections/initializers/sectionInitializer3.h
        mars2grib/backend/sections/initializers/sectionInitializer4.h
        mars2grib/backend/sections/initializers/sectionInitializer5.h
        mars2grib/backend/sections/initializers/sectionInitializerCore.h
        mars2grib/backend/sections/initializers/sectionRegistry.h
        mars2grib/backend/sections/resolver/ActiveConceptsData.h
        mars2grib/backend/sections/resolver/CompressionMask.h
        mars2grib/backend/sections/resolver/Recipe.h
        mars2grib/backend/sections/resolver/Recipes.h
        mars2grib/backend/sections/resolver/ResolvedTemplateData.h
        mars2grib/backend/sections/resolver/SectionLayoutData.h
        mars2grib/backend/sections/resolver/SectionTemplateSelector.h
        mars2grib/backend/sections/resolver/Select.h
        mars2grib/backend/sections/resolver/TemplateSignatureKey.h
        mars2grib/backend/sections/resolver/dsl.h
        mars2grib/backend/tables/backgroundProcess.h
        mars2grib/backend/tables/derivedForecast.h
        mars2grib/backend/tables/productionStatusOfProcessedData.h
        mars2grib/backend/tables/shapeOfTheReferenceSystem.h
        mars2grib/backend/tables/significanceOfReferenceTime.h
        mars2grib/backend/tables/timeUnits.h
        mars2grib/backend/tables/typeOfEnsembleForecast.h
        mars2grib/backend/tables/typeOfGeneratingProcess.h
        mars2grib/backend/tables/typeOfInterval.h
        mars2grib/backend/tables/typeOfProcessedData.h
        mars2grib/backend/tables/typeOfStatisticalProcessing.h
        mars2grib/backend/tables/typeOfTimeIntervals.h
        mars2grib/frontend/GribHeaderLayoutData.h
        mars2grib/frontend/header/EncodingPlan.h
        mars2grib/frontend/header/SpecializedEncoder.h
        mars2grib/frontend/make_HeaderLayout.h
        mars2grib/frontend/normalization/normalization.h
        mars2grib/frontend/normalization/normalizeMarsDict.h
        mars2grib/frontend/normalization/normalizeMiscDict.h
        mars2grib/frontend/normalization/per_key/SanitizationRegistry.h
        mars2grib/frontend/normalization/per_key/mars/All.h
        mars2grib/frontend/normalization/per_key/mars/activity.h
        mars2grib/frontend/normalization/per_key/mars/anoffset.h
        mars2grib/frontend/normalization/per_key/mars/channel.h
        mars2grib/frontend/normalization/per_key/mars/chem.h
        mars2grib/frontend/normalization/per_key/mars/class.h
        mars2grib/frontend/normalization/per_key/mars/dataset.h
        mars2grib/frontend/normalization/per_key/mars/date.h
        mars2grib/frontend/normalization/per_key/mars/direction.h
        mars2grib/frontend/normalization/per_key/mars/domain.h
        mars2grib/frontend/normalization/per_key/mars/experiment.h
        mars2grib/frontend/normalization/per_key/mars/expver.h
        mars2grib/frontend/normalization/per_key/mars/frequency.h
        mars2grib/frontend/normalization/per_key/mars/generation.h
        mars2grib/frontend/normalization/per_key/mars/grid.h
        mars2grib/frontend/normalization/per_key/mars/hdate.h
        mars2grib/frontend/normalization/per_key/mars/htime.h
        mars2grib/frontend/normalization/per_key/mars/ident.h
        mars2grib/frontend/normalization/per_key/mars/instrument.h
        mars2grib/frontend/normalization/per_key/mars/level.h
        mars2grib/frontend/normalization/per_key/mars/levelist.h
        mars2grib/frontend/normalization/per_key/mars/levtype.h
        mars2grib/frontend/normalization/per_key/mars/method.h
        mars2grib/frontend/normalization/per_key/mars/model.h
        mars2grib/frontend/normalization/per_key/mars/number.h
        mars2grib/frontend/normalization/per_key/mars/origin.h
        mars2grib/frontend/normalization/per_key/mars/packing.h
        mars2grib/frontend/normalization/per_key/mars/param.h
        mars2grib/frontend/normalization/per_key/mars/realization.h
        mars2grib/frontend/normalization/per_key/mars/resolution.h
        mars2grib/frontend/normalization/per_key/mars/stattype.h
        mars2grib/frontend/normalization/per_key/mars/step.h
        mars2grib/frontend/normalization/per_key/mars/stream.h
        mars2grib/frontend/normalization/per_key/mars/system.h
        mars2grib/frontend/normalization/per_key/mars/time.h
        mars2grib/frontend/normalization/per_key/mars/timespan.h
        mars2grib/frontend/normalization/per_key/mars/truncation.h
        mars2grib/frontend/normalization/per_key/mars/type.h
        mars2grib/frontend/normalization/per_key/mars/wavelength.h
        mars2grib/frontend/resolution/resolveActiveConcepts.h
        mars2grib/frontend/resolution/resolveSectionsLayout.h
        mars2grib/frontend/resolution/section-recipes/SectionTemplateSelectors.h
        mars2grib/frontend/resolution/section-recipes/impl/section0Recipes.h
        mars2grib/frontend/resolution/section-recipes/impl/section1Recipes.h
        mars2grib/frontend/resolution/section-recipes/impl/section2Recipes.h
        mars2grib/frontend/resolution/section-recipes/impl/section3Recipes.h
        mars2grib/frontend/resolution/section-recipes/impl/section4Recipes.h
        mars2grib/frontend/resolution/section-recipes/impl/section5Recipes.h
        mars2grib/utils/configConverter.h
        mars2grib/utils/dictionary_traits/dictaccess_codes_handle.h
        mars2grib/utils/dictionary_traits/dictaccess_eckit_configuration.h
        mars2grib/utils/dictionary_traits/dictionary_access_traits.h
        mars2grib/utils/enableOptions.h
        mars2grib/utils/generalUtils.h
        mars2grib/utils/logUtils.h
        mars2grib/utils/mars2gribExceptions.h
        mars2grib/utils/paramMatcher.h
        mars2grib/utils/type_traits_name.h
    )
    set( mars2grib_libs eckit_geo )
endif()

ecbuild_add_library(

    TARGET metkit

    INSTALL_HEADERS LISTED

    HEADER_DESTINATION
        ${INSTALL_INCLUDE_DIR}/metkit

    PERSISTENT
        ${metkit_persistent_srcs}

    SOURCES
        ${metkit_srcs}

    PUBLIC_INCLUDES
       $<BUILD_INTERFACE:${PROJECT_BINARY_DIR}/src>
       $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/src>
       $<BUILD_INTERFACE:${CMAKE_CURRENT_BINARY_DIR}> # for metkit_version.h

    PRIVATE_LIBS
        "${odc_libs}"

    PUBLIC_LIBS
        eckit
        eckit_option
        ${grib_libs}
        ${mars2grib_libs}
)

if( HAVE_MARS2GRIB_PYTHON )
    add_subdirectory(mars2grib/api/pymars2grib)
endif()
