#pragma once

#include <exception>
#include <string>

#include "eckit/exception/Exceptions.h"
#include "eckit/log/Log.h"

#include "metkit/config/LibMetkit.h"
#include "metkit/mars2grib/utils/mars2grib-exception.h"


namespace metkit::mars2grib::backend::deductions {

// TODO MIVAL: These tables should be generated by a python script
// from eccodes definitions at build time because they may change over time
// There is no known (to the author) automatic way to get these tables from eccodes directly
// or to set these values in grib messages via string or via eccodes API.

// eccodes codes table 1.3
enum class ProductionStatusOfProcessedData : long {
    OperationalProducts              = 0,
    OperationalTestProducts          = 1,
    ResearchProducts                 = 2,
    ReanalysisProducts               = 3,
    TiggeOperational                 = 4,
    TiggeTest                        = 5,
    S2SOperationalProducts           = 6,
    S2STestProducts                  = 7,
    UerraOperational                 = 8,
    UerraTest                        = 9,
    CopernicusRegionalReanalysis     = 10,  // CARRA / CERRA
    CopernicusRegionalReanalysisTest = 11,  // CARRA / CERRA
    DestinationEarth                 = 12,
    DestinationEarthTest             = 13,
    Missing                          = 255
};


// TODO MIVAL: this logic at the moment is very weak, as it does not cover all cases
// need interaction with DGOV team to improve/define this mapping

// grib2 section 1 octet 20
template <class MarsDict_t, class ParDict_t>
ProductionStatusOfProcessedData productionStatusOfProcessed(const MarsDict_t& mars, const ParDict_t& par) {

    using metkit::mars2grib::utils::dict_traits::get_or_throw;
    using metkit::mars2grib::utils::exceptions::Mars2GribDeductionException;

    try {

        // Get mars type from dictionary
        std::string marsClass  = get_or_throw<std::string>(mars, "class");
        std::string marsType   = get_or_throw<std::string>(mars, "type");
        std::string marsStream = get_or_throw<std::string>(mars, "stream");

        // TODO MIVAL: Need to check the value of `class` is valid in mars

        // Deduce typeOfProcessedData from mars type
        if (marsClass == "d1") {
            // This is mandatory for DestinE because it is used inside eccodes
            // to allocate the proper "localUseSection" template.
            return ProductionStatusOfProcessedData::DestinationEarth;
        }
        else {
            // TODO MIVAL: Here I set the default to missing, but need to clarify with DGOV team,
            // This need to be inferred from "type", "class", "stream"
            return ProductionStatusOfProcessedData::Missing;
        };

        // Remove compiler warning
        __builtin_unreachable();
    }
    catch (...) {

        // Rethrow nested exceptions
        std::throw_with_nested(Mars2GribDeductionException(
            "Unable to deduce `productionStatusOfProcessedData` from Mars or Parametrization dictionaries", Here()));
    }

    // Remove compiler warning
    __builtin_unreachable();
};


}  // namespace metkit::mars2grib::backend::deductions
