#pragma once

#include <optional>

#include "eckit/exception/Exceptions.h"
#include "eckit/log/Log.h"

#include "metkit/config/LibMetkit.h"


namespace metkit::mars2grib::backend::deductions {

// TODO MIVAL: These tables should be generated by a python script
// from eccodes definitions at build time because they may change over time
// There is no known (to the author) automatic way to get these tables from eccodes directly
// or to set these values in grib messages via string or via eccodes API.

// eccodes codes table 1.4
enum class TypeOfProcessedData : long {
    AnalysisProducts                    = 0,
    ForecastProducts                    = 1,
    AnalysisAndForecastProducts         = 2,
    ControlForecastProducts             = 3,
    PerturbedForecastProducts           = 4,
    ControlAndPerturbedForecastProducts = 5,
    ProcessedSatelliteObservations      = 6,
    ProcessedRadarObservations          = 7,
    EventProbability                    = 8,
    ExperimentalData                    = 9,
    MlBasedForecast                     = 10,
    Missing                             = 255
};


// grib2 section 1 octet 21
template <class MarsDict_t, class ParDict_t>
TypeOfProcessedData typeOfProcessed(const MarsDict_t& mars, const ParDict_t& par) {

    using metkit::mars2grib::utils::dict_traits::get_or_throw;
    using metkit::mars2grib::utils::exceptions::Mars2GribDeductionException;

    try {

        // TODO MIVAL: For the moment I focus on the automatic deduction only

        // Get mars type from dictionary
        std::string marsClass  = get_or_throw<std::string>(mars, "class");
        std::string marsType   = get_or_throw<std::string>(mars, "type");
        std::string marsStream = get_or_throw<std::string>(mars, "stream");


        // TODO MIVAL: Need to check the value of `class` is valid in mars

        // Deduce typeOfProcessedData from mars type
        if (marsType == "an") {
            return TypeOfProcessedData::AnalysisProducts;
        }
        else if (marsType == "fc") {
            return TypeOfProcessedData::ForecastProducts;
        }
        else if (marsType == "pf") {
            return TypeOfProcessedData::PerturbedForecastProducts;
        }
        else if (marsType == "cf") {
            return TypeOfProcessedData::ControlForecastProducts;
        }
        else if (marsType == "ssd" || marsType == "gsd") {
            return TypeOfProcessedData::ProcessedSatelliteObservations;
        }
        else {
            return TypeOfProcessedData::Missing;
        }
    }
    catch (...) {

        // Rethrow nested exceptions
        std::throw_with_nested(Mars2GribDeductionException(
            "Unable to get `typeOfProcessedData` from Mars or Parametrization dictionaries", Here()));
    }
};


}  // namespace metkit::mars2grib::backend::deductions
