name: cd

on:
  push:
    tags:
      - '**'

jobs:
  deploy:
    uses: ecmwf/reusable-workflows/.github/workflows/create-package.yml@v2
    secrets: inherit
  wheel-wrapper:
    uses: ./.github/workflows/build-wheel-wrapper.yml
    secrets: inherit
  wheel-python:
    uses: ecmwf/reusable-workflows/.github/workflows/cd-pypi.yml@v2
    secrets: inherit
    needs:
      - wheel-wrapper
