name: ci

on:
  # Trigger the workflow on push to all branches, except master, develop and on tag creation
  push:
    branches-ignore:
      - 'master'
      - 'develop'
    tags-ignore:
      - '**'

jobs:
  # Calls a reusable CI workflow to build & test the current repository.
  ci:
    name: ci
    uses: ./.github/workflows/reusable-ci.yml
    with:
      metkit: ecmwf/metkit@${{ github.sha }}
    secrets: inherit
