name: ci

on:
  # Trigger the workflow on push to master or develop, except tag creation
  push:
    branches:
      - 'master'
      - 'develop'
    tags-ignore:
      - '**'

  # Trigger the workflow on pull request
  pull_request: ~

  # Trigger the workflow manually
  workflow_dispatch: ~

jobs:
  # Run CI including downstream packages on self-hosted runners
  downstream-ci:
    name: downstream-ci
    uses: ecmwf-actions/downstream-ci/.github/workflows/downstream-ci.yml@main
    with:
      metkit: ecmwf/metkit@${{ github.event.pull_request.head.sha || github.sha }}
    secrets: inherit

  # # Build downstream packages on HPC
  # downstream-ci-hpc:
  #   name: metkit-downstream-ci-hpc
  #   if: github.event_name == "pull_request"
  #   uses: ecmwf-actions/downstream-ci/.github/workflows/downstream-ci-hpc.yml@metkit
  #   with:
  #     metkit: ecmwf/metkit@${{ github.event.pull_request.head.sha }}
  #   secrets: inherit
