name: reusable-ci

on:
  workflow_call:
    inputs:
      metkit:
        required: false
        type: string
        default: 'ecmwf/metkit@develop'
      eccodes:
        required: false
        type: string
        default: 'ecmwf/eccodes@develop'
      eckit:
        required: false
        type: string
        default: 'ecmwf/eckit@develop'

jobs:
  ci:
    name: metkit-ci
    uses: ecmwf-actions/reusable-workflows/.github/workflows/ci.yml@v2
    with:
      repository: ${{ inputs.metkit }}
      name_prefix: metkit-
      build_package_inputs: |
        repository: ${{ inputs.metkit }}
        self_coverage: true
        dependencies: |
          ecmwf/ecbuild
          MathisRosenhauer/libaec@master
          ${{ inputs.eccodes }}
          ${{ inputs.eckit }}
        dependency_branch: develop
        parallelism_factor: 8
    secrets: inherit
