name: reusable-ci

on:
  workflow_call:
    inputs:
      metkit:
        required: false
        type: string
      eccodes:
        required: false
        type: string
      eckit:
        required: false
        type: string

jobs:
  ci:
    name: metkit-ci
    uses: ecmwf-actions/reusable-workflows/.github/workflows/ci.yml@v2
    with:
      repository: ${{ inputs.metkit || 'ecmwf/metkit@develop' }}
      name_prefix: metkit-
      build_package_inputs: |
        repository: ${{ inputs.metkit || 'ecmwf/metkit@develop' }}
        self_coverage: true
        dependencies: |
          ecmwf/ecbuild
          MathisRosenhauer/libaec@master
          ${{ inputs.eccodes || 'ecmwf/eccodes' }}
          ${{ inputs.eckit || 'ecmwf/eckit' }}
        dependency_branch: develop
        parallelism_factor: 8
    secrets: inherit
